# Generated by Django 5.2.6 on 2025-11-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pointage', models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ'), ('pause_debut', 'Début Pause'), ('pause_fin', 'Fin Pause')], max_length=20)),
                ('datetime_pointage', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appareil_id', models.CharField(blank=True, max_length=100)),
                ('synced_with_odoo', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-datetime_pointage'],
                'indexes': [models.Index(fields=['personnel', 'datetime_pointage'], name='pointage_po_personn_aaf184_idx')],
            },
        ),
    ]
